# 站点配置
title: Faynmen

# 构建设置
markdown: kramdown
theme: jekyll-theme-cayman

# 核心配置：定义 Collections
collections:
  notes:
    output: true # 确保生成 HTML 文件
    permalink: /notes/:path/ # 使用文件路径作为永久链接的一部分

# 告诉 Jekyll 哪些目录需要被处理，但请注意：
# Jekyll Collections 默认只支持顶层目录。
# 解决办法：使用 defaults 配置和包含/排除，或者直接在 collections 中指定。
# 对于 GitHub Pages，我们主要依赖 defaults 来设置 Front Matter。

# ------------------------------------
# 3. 默认 Front Matter (为笔记文件应用布局)
# ------------------------------------
# 强制所有在 'folder1' 和 'folder2' 下的文件使用 'post' 布局
defaults:
  - scope:
      path: "ps"
    values:
      layout: "post"
      collection: "notes" # 确保它们被视为 notes 集合的一部分
  - scope:
      path: "CSharp"
    values:
      layout: "post"
      collection: "notes" # 确保它们被视为 notes 集合的一部分



# Exclude list 排除列表
exclude:
  - README.md
  - LICENSE
