# 站点配置
title: Faynmen

# 构建设置
markdown: kramdown
theme: jekyll-theme-cayman
github_button: false

# 核心配置：定义 Collections
collections:
  # PS 集合 (Powershell)
  ps_notes:
    output: true          # 确保渲染
    label: ps             # 告诉 Jekyll 源文件夹是 ps
    permalink: /ps/:path/     
    
# 设置默认值 (应用布局)
defaults:
  # 应用于 PS 集合的文件
  - scope:
      path: ""
      type: ps_notes      # 必须与 collections 中定义的名称 'ps_notes' 一致
    values:
      layout: post        # 引用 Minima 主题中的 post 布局

# Exclude list 排除列表
exclude:
  - README.md
  - LICENSE
